### ISSUE TITLE
Nova atualização

### ISSUE THREAD

**Issue by ianchamba** [Open-Pix/openpix-whmcs#1]
Fiz uma atualização lá no repositório, não sei se vai ser interessante pra todo mundo, mas automatizei o cancelamento da cobrança expirada na OpenPix dentro do WHMCS. Se tiver ideias do que incrementar tbm, pode mandar lá no repositório que eu atualizo. Vlw pelos créditos.

**Comment by sibelius** [comment]
te dei acesso ao repo

**Comment by ianchamba** [comment]
Thanks
